language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - name: build
  - name: test
    if: type = pull_request
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build
    - stage: test
      script:
        - ./gradlew test
    - stage: deploy
      script:
        - ./deploy-scripts/deploy.sh
