language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - name: build
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build test
    - stage: deploy
      script:
        - git reset --hard HEAD
        - git clean -f
        - git checkout master
        - git pull origin master
        - ./deploy-scripts/deploy.sh
