language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - name: build
  - name: deploy-site
    if: branch = master AND type != pull_request
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build test
    - stage: deploy-site
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem install bundler
      script:
        - bundle install --gemfile docs/Gemfile --path vendor/bundle && BUNDLE_GEMFILE=./docs/Gemfile bundle exec jekyll build -s docs -b /hood -d pub-dir
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: pub-dir
    - stage: deploy
      script:
        - ./deploy-scripts/deploy.sh
