title: Hood
#-------------------------
name: Hood
#-------------------------
description: Hood is a plugin to compare benchmarks and set the result as a Github status for a Pull Request. Hood is built on Arrow, a Functional companion to Kotlin's Standard Library.
#-------------------------
author: 47 Degrees
keywords: functional-programming, kotlin-library, arrow, monads, monad-transformers, functional-data-structure, kotlin, fp-types, adt, free-monads, tagless-final, mtl, for-comprehension, category-theory
#-------------------------
url: https://www.47deg.com
#-------------------------
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
#-------------------------
permalink: pretty
#-------------------------
